/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CvvcfGeDH5U
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function registro() {
  return (

    (<div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-center"><br /><br />
      <img src="/logo.png" alt="" /><br /><br />
        <h1 className="text-3xl font-bold">Regístrate</h1>
        <p className="text-muted-foreground">Crea una cuenta para acceder a todas las funcionalidades.</p>
      </div>
      <div className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="name">Nombre</Label>
            <Input id="name" placeholder="Ingresa tu nombre" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Correo electrónico</Label>
            <Input id="email" type="email" placeholder="ejemplo@dominio.com" required />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Contraseña</Label>
          <Input id="password" type="password" required />
        </div>
        <Button type="submit" className="w-full">
          Registrarse
        </Button>
      </div>
    </div>)
  );
}
